baseURL = "https://www.agustinventura.dev"
enableRobotsTXT = true
enableGitInfo = true

[params]
  metricoolHash = "3a8842cdb94b360d5b510812aa0274b"
  [params.article]
    showComments = true

[minify]
  minifyOutput = true

[services]
  [services.disqus]
    shortname = 'agustinventura'